package com.officedubac.project.models;

public enum Role
{
    ADMIN,
    INSPECTEUR_ACADEMIE,
    ASSESSEUR_UNIV,
    CHEF_ETABLISSEMENT,
    SUPERVISEUR,
    SCOLARITE,
    PEDAGOGIE,
    PLANIFICATION,
    AGENT_DE_SAISIE,
    RECEPTIONNISTE,
    VIGNETTES_COUPONS,
    AUTORISATION_RECEPTION,
    PRESIDENT_JURY,
    AUTRES,
    EXAMINATEUR,
    SECRETAIRE_DE_JURY,
    DEMSG,
    FINANCE_COMPTA
}
